// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  kbSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Microsoft',
      link: {
        type: 'generated-index',
        slug: 'category/microsoft',
        description: 'Windows Server, Active Directory, Microsoft 365 and Azure how-tos and fixes.',
      },
      items: [{type: 'autogenerated', dirName: 'microsoft'}],
    },
    {
      type: 'category',
      label: 'VMware',
      link: {
        type: 'generated-index',
        slug: 'category/vmware',
        description: 'ESXi, vCenter and virtualization troubleshooting guides.',
      },
      items: [{type: 'autogenerated', dirName: 'vmware'}],
    },
    {
      type: 'category',
      label: 'Networking',
      link: {
        type: 'generated-index',
        slug: 'category/networking',
        description: 'DNS, DHCP, routing and connectivity troubleshooting.',
      },
      items: [{type: 'autogenerated', dirName: 'networking'}],
    },
    'about',
  ],
};

export default sidebars;
