// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  kbSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Microsoft',
      link: {
        type: 'generated-index',
        slug: 'category/microsoft',
        description: 'Windows Server, Active Directory, Microsoft 365 and Azure how-tos and fixes.',
      },
      items: [{type: 'autogenerated', dirName: 'microsoft'}],
    },
    {
      type: 'category',
      label: 'VMware',
      link: {
        type: 'generated-index',
        slug: 'category/vmware',
        description: 'ESXi, vCenter and virtualization troubleshooting guides.',
      },
      items: [{type: 'autogenerated', dirName: 'vmware'}],
    },
    {
      type: 'category',
      label: 'Networking',
      link: {
        type: 'generated-index',
        slug: 'category/networking',
        description: 'DNS, DHCP, routing and connectivity troubleshooting.',
      },
      items: [{type: 'autogenerated', dirName: 'networking'}],
    },
    {
      type: 'category',
      label: 'Tools',
      collapsed: false,
      items: [
        {type: 'link', label: 'M365 Domain and Tenant Lookup', href: '/tools/m365-lookup'},
         {type: 'link', label: 'SPF, DKIM and DMARC Checker', href: '/tools/email-auth-checker'},
      ],
    },
    {
      type: 'category',
      label: 'Scripts',
      collapsed: false,
      link: {type: 'doc', id: 'scripts/scripts'},
      items: ['scripts/reset-windows-update'],
    },
    {type: 'link', label: 'Blog', href: '/blog'},
    'about',
  ],
};

export default sidebars;
